import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ProjectsProvider from "./components/ProjectsProvider";
import Footer from "./components/Footer";
import Header from "./components/Header";
import { Analytics } from "@vercel/analytics/react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-background text-foreground`}
      >
        <div className="flex flex-col min-h-screen">
          <ProjectsProvider>
            <Header />
            <div className="flex-grow mt-7 md:mt-20">{children}</div>
          </ProjectsProvider>
          <Footer />
        </div>
        <Analytics />
      </body>
    </html>
  );
}
